apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedores-deployment
  labels:
    app: proveedores-deployment
spec:
  selector:
    matchLabels:
      app: proveedores-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: proveedores-deployment
    spec:
      containers:
        - name: proveedores
          image: gaspitas241/proveedores
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-service:8761/eureka
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/milkstgo
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: proveedores-service
  labels:
    app: proveedores-service
spec:
  selector:
    app: proveedores-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer