server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${EUREKA:localhost}:8761/eureka
  instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      routes:
        - id: pago-service
          uri: lb://pago-service
          predicates:
            - Path=/pago/**
        - id: acopios-service
          uri: lb://acopios-service
          predicates:
            - Path=/acopios/**
        - id: proveedores-service
          uri: lb://proveedores-service
          predicates:
            - Path=/proveedores/**
        - id: laboratorio-service
          uri: lb://laboratorio-service
          predicates:
            - Path=/laboratorio/**